import pygame

def __response_undefined(response:bool = False, error:bool = False):
    if response:
        print("__respone_undefined for keyaction")
    if error:
        raise Exception("__respone_undefined for keyaction")

base_keyboard_map:dict = {
    pygame.K_a: "a",
    pygame.K_b: "b",
    pygame.K_c: "c",
    pygame.K_d: "d",
    pygame.K_e: "e",
    pygame.K_f: "f",
    pygame.K_g: "g",
    pygame.K_h: "h",
    pygame.K_i: "i",
    pygame.K_j: "j",
    pygame.K_k: "k",
    pygame.K_l: "l",
    pygame.K_m: "m",
    pygame.K_n: "n",
    pygame.K_o: "o",
    pygame.K_p: "p",
    pygame.K_q: "q",
    pygame.K_r: "r",
    pygame.K_s: "s",
    pygame.K_t: "t",
    pygame.K_u: "u",
    pygame.K_v: "v",
    pygame.K_w: "w",
    pygame.K_x: "x",
    pygame.K_y: "y",
    pygame.K_z: "z",
}

empty_keyup_responses:dict = {
    "a": __response_undefined,
    "b": __response_undefined,
    "c": __response_undefined,
    "d": __response_undefined,
    "e": __response_undefined,
    "f": __response_undefined,
    "g": __response_undefined,
    "h": __response_undefined,
    "i": __response_undefined,
    "j": __response_undefined,
    "k": __response_undefined,
    "l": __response_undefined,
    "m": __response_undefined,
    "n": __response_undefined,
    "o": __response_undefined,
    "p": __response_undefined,
    "q": __response_undefined,
    "r": __response_undefined,
    "s": __response_undefined,
    "t": __response_undefined,
    "u": __response_undefined,
    "v": __response_undefined,
    "w": __response_undefined,
    "x": __response_undefined,
    "y": __response_undefined,
    "z": __response_undefined,
}

empty_keydown_responses:dict = {
    "a": __response_undefined,
    "b": __response_undefined,
    "c": __response_undefined,
    "d": __response_undefined,
    "e": __response_undefined,
    "f": __response_undefined,
    "g": __response_undefined,
    "h": __response_undefined,
    "i": __response_undefined,
    "j": __response_undefined,
    "k": __response_undefined,
    "l": __response_undefined,
    "m": __response_undefined,
    "n": __response_undefined,
    "o": __response_undefined,
    "p": __response_undefined,
    "q": __response_undefined,
    "r": __response_undefined,
    "s": __response_undefined,
    "t": __response_undefined,
    "u": __response_undefined,
    "v": __response_undefined,
    "w": __response_undefined,
    "x": __response_undefined,
    "y": __response_undefined,
    "z": __response_undefined,
}